[options]
packages = find:
include_package_data = True

[options.entry_points]
babel.extractors =
                 ckan = ckan.lib.extract:extract_ckan

[extract_messages]
keywords = translate isPlural
add_comments = TRANSLATORS:
output_file = ckanext/apidocs/i18n/ckanext-apidocs.pot
width = 80

[init_catalog]
domain = ckanext-apidocs
input_file = ckanext/apidocs/i18n/ckanext-apidocs.pot
output_dir = ckanext/apidocs/i18n

[update_catalog]
domain = ckanext-apidocs
input_file = ckanext/apidocs/i18n/ckanext-apidocs.pot
output_dir = ckanext/apidocs/i18n
previous = true

[compile_catalog]
domain = ckanext-apidocs
directory = ckanext/apidocs/i18n
statistics = true
