"""Interfaces provided by ckanext-apidocs for other extensions.

Example::

    import ckan.plugins as p

    from ckanext.apidocs import interfaces


    class MyPlugin(p.SingletonPlugin):
        p.implements(interfaces.IApidocs)
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from ckan.plugins.interfaces import Interface


class IApidocs(Interface):
    """Extend the OpenAPI specification generated by ckanext-apidocs."""

    def modify_openapi_spec(self, spec: dict[str, Any]) -> dict[str, Any] | None:
        """Modify the generated OpenAPI document.

        Called once, after every action has been documented. Implementations
        can return a new document, or ``None`` to leave the document
        unchanged.
        """
        return spec

    def get_action_badges(
        self, action_name: str, origin: str | None
    ) -> Sequence[str] | None:
        """Return extra badges for the given action.

        Badges are rendered next to the action path in the Swagger UI and
        stored in the ``x-badges`` extension of the operation.
        """
        return None
